---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function from Cloud Formation by Wolfgang Unger'

Parameters:
  OwnerName:
    Description: An owner name, used in tags
    Type: String
    Default: "wolfgang.unger"
  Stage:
    Description: the stage for the environment
    Type: String    

Resources:

  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
        RoleName: lambda-exec-role    
        Path: "/"    
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "lambda.amazonaws.com"
              Action: 
                  - "sts:AssumeRole" 
        Policies:
            - PolicyName: wu-AmazonSSMFullAccess
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                        - 'cloudwatch:PutMetricData'
                        - 'ds:CreateComputer'
                        - 'ds:DescribeDirectories'
                        - 'ec2:DescribeInstanceStatus'
                        - 'logs:*'
                        - 'ssm:*'
                    Resource: '*'

  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            ZipFile: >
                def lambda_handler(event, context):
                return 'Hello from Lambda'
        Description: Test with Cloud Formation
        FunctionName: wu-HelloWorldPyByCF
        Handler: index.lambda_handler
        Runtime: python2.7
        Role: !Ref LambdaRole
        Tags:
            - Key: Name
              Value: 'ppQueue1'
            - Key: Owner
              Value: !Ref OwnerName         
            - Key: Stage
              Value: !Ref Stage   